name: Deploy and Run Python Script

on:
  push:
    branches:
      - main  # Runs when code is pushed to "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Specify Python version

      - name: Debug - Check if GOOGLE_API_KEY is Set
        run: |
          if [ -z "$GOOGLE_API_KEY" ]; then
            echo "GOOGLE_API_KEY is NOT set!"
            exit 1
          else
            echo "GOOGLE_API_KEY is set successfully!"
          fi
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Install dependencies
        run: pip install -r requirements.txt  # Install dependencies

      - name: Set environment variable
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: echo "GOOGLE_API_KEY is set"

      - name: Run Dashboard Script
        run: python dashboard.py  # Run the Streamlit dashboard
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Run YouTube Analysis Script
        run: python youtube_analysis.py  # Run the YouTube script
